#!/bin/sh 


export EVALFUNC_MAXNODEIDS=140

export EVALFUNC_FAKEWORKTIME=0.1

export EVALFUNC_ANSWERIDS=11,44,111,133

echo RMB "--------  0.1 work time --------"
echo
echo RMB "-------------------------------- 1"

/usr/bin/time -p  mpiexec -n 2 ./p5 9999

echo RMB "-------------------------------- 2"

/usr/bin/time -p  mpiexec -n 3 ./p5 9999

echo RMB "-------------------------------- 4"

/usr/bin/time -p  mpiexec -n 5 ./p5 9999
